<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Loops (Need) Exercises</span></div>

# Exercise 1

Convert each temperature to Fahrenheit and print both temperatures.

In [30]:
temperature_celsius=[0,5,10,15,20,25,30,35,40,45,50]

In [60]:
import numpy as np

c_array=np.array(temperature_celsius)
f_array=(c_array*9/5+32).astype(int)
print(c_array)
print(f_array)

[ 0  5 10 15 20 25 30 35 40 45 50]
[ 32  41  50  59  68  77  86  95 104 113 122]


In [62]:
temperature_fahrenheit=f_array.tolist()
print(temperature_fahrenheit)

[32, 41, 50, 59, 68, 77, 86, 95, 104, 113, 122]


In [70]:
for index, c in enumerate(temperature_celsius):
    f=temperature_fahrenheit[index]
    print(f"{c}\N{degree sign}C, {f}\N{degree sign}F")

0°C, 32°F
5°C, 41°F
10°C, 50°F
15°C, 59°F
20°C, 68°F
25°C, 77°F
30°C, 86°F
35°C, 95°F
40°C, 104°F
45°C, 113°F
50°C, 122°F


# Exercise 2

## Example:

Double loop: loop within a loop.

In [75]:
for letter in ['A','B','C']:
    for number in [1,2,3]:
        print(f'{letter}{number}',end='\t')  # Adds a tab after every number.
    print('\n')                              # Prints every letter at a new line.

A1	A2	A3	

B1	B2	B3	

C1	C2	C3	



## Task:

Print a multiplication able (up to 5) for numbers 1-5 using **nested** `for` loops.

In [116]:
multiplier_list=[1,2,3,4,5]
multiplicand_list=[1,2,3,4,5]
multiplier_array=np.array(multiplier_list)
multiplicand_array=np.array(multiplicand_list)

In [158]:
for multiplicand in multiplicand_array:
    for multiplier in multiplier_array:
        print(f"{multiplier*multiplicand}",end='\t')
    print(f"{multiplier}:",end='\n')

1	2	3	4	5	5:
2	4	6	8	10	5:
3	6	9	12	15	5:
4	8	12	16	20	5:
5	10	15	20	25	5:


In [125]:
multiplier_array*multiplicand_array

array([ 1,  4,  9, 16, 25])

In [117]:
print(multiplier)

for multiplier in [1,2,3,4,5]:
    print(f'{multiplier}:{multiplicand_list}')

5
1:[1, 2, 3, 4, 5]
2:[1, 2, 3, 4, 5]
3:[1, 2, 3, 4, 5]
4:[1, 2, 3, 4, 5]
5:[1, 2, 3, 4, 5]


In [106]:
#product_list=multiplier_list*multiplicand_list
#print(product_list)

product_array=multiplier_array*multiplicand_array
print(product_array)

[ 5 10 15 20 25]


In [108]:
for multiplier in [1,2,3,4,5]:
    for multiplicand in product_array:
        print(f"{multiplier} : {multiplicand}",end='\t')
    print('\n')

1 : 5	1 : 10	1 : 15	1 : 20	1 : 25	

2 : 5	2 : 10	2 : 15	2 : 20	2 : 25	

3 : 5	3 : 10	3 : 15	3 : 20	3 : 25	

4 : 5	4 : 10	4 : 15	4 : 20	4 : 25	

5 : 5	5 : 10	5 : 15	5 : 20	5 : 25	



In [ ]:
print(f"{multiplier} : {multiplier*multiplicand})