<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

Accessing and modifying structures.
Better understandin of similarities and differences between lists, NumPy arrays and dictionaries.

# 1 Subsetting: Indexing and Slicing

Subsetting: **select** a subset of data in list/ array.
How to subset?:
- Indexing: select **1** element.
- Slicing: selecting **range** of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

Slicing gives range of elements.\
Need to specify 2 indices to indicate start and end.\
Applies for **both** lists and arrays.

In [4]:
import numpy as np
py_list=["a1","b2","c3","d4","e5","f6","g7","h8","i9","j10"]
np_array=np.array(py_list)

x=py_list
x=np_array

|Syntax|Result||Note|
|:-|:-|:-|:-|
|`x[0]`|First element|`'a1'`||
|`x[-1]`|Last element|`'j10'`||
|`x[0:3]`|Index 0 to 2|`['a1','b2','c3']`|Gives $3-0=3$ elements.|
|`x[1:6]`|Index 1 to 5|`['b2','c3','d4','e5','f6']`|Gives $6-1=5$ elements.|
|`x[1:6:2]`|Index 1 to 5 in steps of 2|`['b2','d4','f6']`|Gives every other of $6-1=5$ elements.|
|`x[5:]`|Index 5 to the end|`['f6','g7','h8','i9','j10']`|Gives `len(x)`$-5=5$ elements.|
|`x[:5]`|Index 0 to 4|`['a1','b2','c3','d4','e5']`|Gives $5-0=5$ elements.|
|`x[5:2:-1]`|Index 5 to 3 (i.e. reverse order)|`['f6','e5',d4']`|Gives $5-2=3$ elements.|
|`x[::-1]`|Reverse list|`['j10','i9','e8',...,'b2','a1']`||

Slicing with `[i:j]` gives total of `j-i` elements.\
Slice starts at `i` and ends at `j-1`.

## 1.2 Arrays only | Subsetting by masking

How it works:

In [8]:
np_array=np.array([1,2,3,4,5,6,7,8,9,10])
my_mask=np_array>3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

Shortcut:

In [10]:
np_array[np_array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

Asks what elements in np_array is greater than 3.\
Returns T/F accordingly.\
From this, can ask NumPy to show **only** those that are `True` (i.e. mask/ hide all other variables except those that are `True`).\
Note: only works for NumPy arrays.

E.g. 1: Invert mask, `NOT`.

In [11]:
np_array[~(np_array>3)]

array([1, 2, 3])

Bitwise NOT: `~`.\
Inverts the mask.

E.g. 2: Combining masks, `AND`.

In [13]:
np_array[(np_array>3)&(np_array<8)]

array([4, 5, 6, 7])

Bitwise AND: `&`.\
Shows something only if **both** masks are true.

E.g. 3: Combining masks, `OR`.

In [15]:
np_array[(np_array>3)|(np_array<8)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Bitwise OR: `|`.\
Shows something if **either** mask is true.

TLDR:
- Use bitwise operators when combining masks with NumPy.
- Use brackets to clarify what the masks do.
|Bitwise Operator|Code|
|:-:|:-:|
|`NOT`|`~`|
|`AND`|`&`|
|`OR`|`\|`|

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

Differences between lists and arrays more apparent with higher dimensions.

In [17]:
py_list_2d=[[1, "A"],[2, "B"],[3, "C"],[4, "D"],[5, "E"],
            [6, "F"],[7, "G"],[8, "H"],[9, "I"],[10, "J"]]
np_array_2d=np.array(py_list_2d)

E.g. 1: What is at position 4 (index 3)?

In [26]:
py_list_2d[3]

[4, 'D']

In [27]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

```
Compare the following ways to code E.g. 1:
```

In [32]:
py_list_2d[3]
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [30]:
print(py_list_2d[3])  # Note Jupyter's feature.
np_array_2d[3]

[4, 'D']


array(['4', 'D'], dtype='<U11')

```
Insight:
- Jupyter's feature is to auto-print last line output.
- By default, Python will not print any outputs unless specified.
- As a habit, use `print()` for all outputs that you want to show.
```

E.g. 2: What is **first** element at position 4 (index 3)?

In [33]:
py_list_2d[3][0]

4

In [40]:
np_array_2d[3,0]

'4'

Syntax for *arrays* use **1 pair** of square brackets `[]`, in contrast to *lists*, which have **n pairs** of `[]` for n-dimensions.\
For *lists*, 1st `[]` indicates index of outer list, 2nd `[]` indicates index of inner/ nested list.

E.g. 3: What are the first 3 elements?

In [35]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [36]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

E.g. 4: What are the first elements of the first 3 lists?

In [53]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [46]:
py_list_2d[:3][0]

[1, 'A']

For 2D lists, if 1st `[]` prints a **range** of lists, 2nd `[]` indicates the **index of the list** amongst the selected range of lists.\
New range of lists re-indexed, starting from 0.\
Works likewise for higher dimension lists.

In [38]:
np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U11')

E.g. 5: ?

In [65]:
py_list_2d[3:6][0]  # Prints index 0 list from new range.

[4, 'D']

In [66]:
np_array_2d[3:6,0]  # Prints index 0 element from each list within specified range.

array(['4', '5', '6'], dtype='<U11')

In [68]:
np_array_2d[:,0]  # Prints index 0 element for all index elements in the outer list.

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

Use `:` to select all index elements in a list.

```
E.g. of 3D list: How to print the 1st '4'?
```

In [44]:
py_3d_list = [[1,2,[3,4]],[1,2,[3,4]]]
print(py_3d_list[0][2][1])

4


```
No specific way to name/ reference each bracket.
Suggested naming:
- 1st '[]': outermost layer.
- 2nd '[]': inner layer.
- 3rd '[]': innermost layer.
```

## 1.4 Growing lists

Slicing syntax of NumPy arrays more inutitive than lists.\
Lists are easy and efficient to grow.\
Growing lists useful for solving differential equations numerically, etc..\
NumPy arrays good for fast math operations, provided their **size doesn't change**.
- Rationale: Speed due to optimised storing of *data in specific order* within memory. When changing size (i.e. adding or removing elements), *creates* new array and *deletes* existing array, which is super inefficient.

E.g. 1: Creating a larger list from a smaller one.

In [70]:
x=[1,2]*5
print(x)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


E.g. 2: 3 ways to grow list by appending 1 element at a time.

In [72]:
x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
print(x)

[1, 2, 3, 4]


In [73]:
x=[1]
x+=[2]
x+=[3]
x+=[4]
print(x)

[1, 2, 3, 4]


In [75]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)

[1, 2, 3, 4]


`[1]` specifies x contains the element 1.\
Subsequent steps are adding elements `[2]`, `[3]` and `[4]` respectively.\
`append()` adds elements to 'x'.\
Execution speeds different between these 3 methods; `append()` is 1.5x faster than the rest.

E.g. 3: 3 ways to incorporate multiple elements.

In [76]:
x=[1,2,3]
x+=[4,5,6]
print(x)

[1, 2, 3, 4, 5, 6]


In [77]:
x=[1,2,3]
x.extend([4,5,6])
print(x)

[1, 2, 3, 4, 5, 6]


In [78]:
x=[1,2,3]
x.append([4,5,6])
print(x)

[1, 2, 3, [4, 5, 6]]


`extend()` adds the list of elements as **individual elements** into the first list.\
`append()` adds the list of elements as a **list** into the first list.

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes